-- First, let's create some demo users in the auth.users table to support sample merchants
-- We'll insert directly into auth.users (this is typically done by Supabase auth, but we can do it for demo purposes)

-- Create demo auth users for our sample merchants
INSERT INTO auth.users (
  instance_id,
  id, 
  aud, 
  role, 
  email, 
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_sent_at,
  new_email,
  email_change_token_new,
  new_email_change_token,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at
) VALUES 
(
  '00000000-0000-0000-0000-000000000000',
  '11111111-1111-1111-1111-111111111111',
  'authenticated',
  'authenticated',
  'demo1@mobilityfirst.ng',
  '$2a$10$dummy.encrypted.password.hash',
  NOW(),
  NOW(),
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  NOW(),
  '{"provider": "email", "providers": ["email"]}',
  '{"first_name": "Demo", "last_name": "Merchant1"}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL
),
(
  '00000000-0000-0000-0000-000000000000',
  '22222222-2222-2222-2222-222222222222',
  'authenticated',
  'authenticated',
  'demo2@hopemobility.rw',
  '$2a$10$dummy.encrypted.password.hash',
  NOW(),
  NOW(),
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  NOW(),
  '{"provider": "email", "providers": ["email"]}',
  '{"first_name": "Demo", "last_name": "Merchant2"}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL
),
(
  '00000000-0000-0000-0000-000000000000',
  '33333333-3333-3333-3333-333333333333',
  'authenticated',
  'authenticated',
  'demo3@africare.ng',
  '$2a$10$dummy.encrypted.password.hash',
  NOW(),
  NOW(),
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  NOW(),
  '{"provider": "email", "providers": ["email"]}',
  '{"first_name": "Demo", "last_name": "Merchant3"}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL
) ON CONFLICT (id) DO NOTHING;

-- Now insert the demo merchants
INSERT INTO public.merchants (user_id, business_name, business_description, business_address, business_city, business_country, business_phone, business_email, merchant_type, status, listing_fee_paid) VALUES
  ('11111111-1111-1111-1111-111111111111', 'MobilityFirst Nigeria', 'Leading provider of quality wheelchairs and mobility aids in Nigeria', '123 Victoria Island Road', 'Lagos', 'Nigeria', '+234-801-234-5678', 'contact@mobilityfirst.ng', 'partner', 'approved', true),
  ('22222222-2222-2222-2222-222222222222', 'Hope Mobility Rwanda', 'Specialized therapeutic footwear and orthotic solutions', '45 Kigali Business District', 'Kigali', 'Rwanda', '+250-788-123-456', 'info@hopemobility.rw', 'partner', 'approved', true),
  ('33333333-3333-3333-3333-333333333333', 'AfriCare Devices', 'Affordable mobility solutions for rural communities', '78 Independence Avenue', 'Abuja', 'Nigeria', '+234-802-456-7890', 'sales@africare.ng', 'vendor', 'approved', true)
ON CONFLICT DO NOTHING;

-- Now insert sample products
INSERT INTO public.products (merchant_id, category_id, name, description, price, market_price_min, market_price_max, stock_quantity, status, images) VALUES
  (
    (SELECT id FROM public.merchants WHERE business_name = 'MobilityFirst Nigeria'),
    (SELECT id FROM public.product_categories WHERE name = 'Mobility Aids'),
    'Standard Manual Wheelchair',
    'Lightweight, durable manual wheelchair with comfortable seating and easy-fold design. Perfect for daily use and transport.',
    250.00,
    300.00,
    450.00,
    15,
    'active',
    ARRAY['https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400']
  ),
  (
    (SELECT id FROM public.merchants WHERE business_name = 'MobilityFirst Nigeria'),
    (SELECT id FROM public.product_categories WHERE name = 'Mobility Aids'),
    'Electric Mobility Scooter',
    'Compact electric scooter with 25km range. Includes basket and LED headlight for safe travel.',
    850.00,
    1000.00,
    1500.00,
    8,
    'active',
    ARRAY['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400']
  ),
  (
    (SELECT id FROM public.merchants WHERE business_name = 'Hope Mobility Rwanda'),
    (SELECT id FROM public.product_categories WHERE name = 'Therapeutic Footwear'),
    'Diabetic Care Shoes',
    'Specially designed shoes for diabetic patients with extra depth and cushioning to prevent foot complications.',
    120.00,
    150.00,
    220.00,
    25,
    'active',
    ARRAY['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400']
  ),
  (
    (SELECT id FROM public.merchants WHERE business_name = 'Hope Mobility Rwanda'),
    (SELECT id FROM public.product_categories WHERE name = 'Daily Living Aids'),
    'Ergonomic Walking Cane',
    'Adjustable walking cane with ergonomic grip and anti-slip tip. Available in multiple colors.',
    35.00,
    45.00,
    65.00,
    50,
    'active',
    ARRAY['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400']
  ),
  (
    (SELECT id FROM public.merchants WHERE business_name = 'AfriCare Devices'),
    (SELECT id FROM public.product_categories WHERE name = 'Accessibility Equipment'),
    'Portable Wheelchair Ramp',
    'Lightweight aluminum ramp that folds for easy transport. Supports up to 300kg and works with most wheelchairs.',
    180.00,
    220.00,
    350.00,
    12,
    'active',
    ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400']
  ),
  (
    (SELECT id FROM public.merchants WHERE business_name = 'AfriCare Devices'),
    (SELECT id FROM public.product_categories WHERE name = 'Exercise & Therapy'),
    'Physical Therapy Exercise Band Set',
    'Complete set of resistance bands for physical therapy and rehabilitation. Includes instruction guide.',
    45.00,
    55.00,
    75.00,
    30,
    'active',
    ARRAY['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400']
  )
ON CONFLICT DO NOTHING;