// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tanajwokvtfkwdweootj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbmFqd29rdnRma3dkd2Vvb3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTQyNzQsImV4cCI6MjA3MDY3MDI3NH0.P8Oyuz-KF_xxJN5pv60BuujPS2S1neLCpDnnBFPFI_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});